### ISSUE TITLE
Kernel panic on Ubuntu 16.04 kenrel 4.4

### ISSUE THREAD

**Issue by iamashwin26** [tanaka1892/mt7601u-ap#2]
The compilation went successful but after i rebooted the keyboard lights started blinking to indicate a kernel panic . removed the usb and then  rebooted then blacklisted mt7601uap but now Firefox crashes randomly. I dont know if the last part is connected to the module but how do i fix the kernel panic when the module is enabled (also now returning to default mt7601u module has no result and wifi isn't displayed in the network section.

**Comment by tanaka1892** [comment]
This does not work with 64 bit kernels. Also I won't provide support for Ubuntu kernels because they somehow mess up the API for drivers. I don't know why. Sorry :(

This is for running a hotspot with the mt7601u. It does not let you connect to networks. Support for this is very limited at the moment. Wait a while and the built-in driver will be improved.
